name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: priyaautkar56/philips-tests:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API tests
        run: pytest tests/test_api.py -v

      - name: Run login tests
        run: pytest tests/test_login.py -v
